---
- name: Installer les dépendances système pour Flask et le venv
  ansible.builtin.apt:
    name: "{{ app_packages }}"
    state: present
    update_cache: yes
  become: true

- name: Créer le répertoire de l'application
  ansible.builtin.file:
    path: "{{ app_dir }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0755'
  become: true

- name: Créer l'environnement virtuel et installer Flask/Psycopg2
  ansible.builtin.pip:
    name: "{{ app_pip_packages }}"
    virtualenv: "{{ app_venv_dir }}"
    virtualenv_command: "{{ app_venv_command }}"
  become: true
  become_user: "{{ app_user }}" 

- name: Déployer le fichier de l'application Flask avec Jinja2
  ansible.builtin.template:
    src: "{{ app_template_src }}"
    dest: "{{ app_file_dest }}"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
  become: true
  notify: Restart Flask App  
- name: Créer le service systemd pour Flask
  ansible.builtin.copy:
    dest: "{{ app_service_dest }}"
    content: |
      [Unit]
      Description={{ app_service_description }}
      After=network.target

      [Service]  
      User={{ app_user }}
      WorkingDirectory={{ app_dir }}
      ExecStart={{ app_service_exec }}
      Restart=always

      [Install]
      WantedBy=multi-user.target
    owner: root
    group: root
  become: true
  notify: Reload Systemd 
- name: S'assurer que l'application est activée et démarrée
  ansible.builtin.systemd:
    name: "{{ app_name }}"
    enabled: yes
    state: started
  become: true

- name: Attendre que le port de l'application soit ouvert
  ansible.builtin.wait_for:
    port: "{{ app_port }}"
    delay: "{{ app_wait_delay }}"
    timeout: "{{ app_wait_timeout }}"

- name: Récupérer la réponse de l'application (Test API)
  ansible.builtin.uri:
    url: "{{ app_test_url }}"
    return_content: yes
  register: api_result

- name: Afficher le résultat du test dans un debug Ansible
  ansible.builtin.debug:
    msg: "L'API a répondu : {{ api_result.content }}"