---
- name: Installer PostgreSQL et ses dépendances 
  ansible.builtin.apt:
    name: "{{ bdd_packages }}"
    state: present
    update_cache: yes
  become: true
  register: apt_result
  until: apt_result is success
  retries: "{{ apt_retries }}"
  delay: "{{ apt_delay }}"

- name: S'assurer que le service PostgreSQL est démarré
  ansible.builtin.service:
    name: "{{ pg_service_name }}"
    state: started
    enabled: yes
  become: true

- name: Créer le groupe de la base de données
  become_user: "{{ pg_system_user }}"
  community.postgresql.postgresql_user:
    name: "{{ db_group }}"
    role_attr_flags: "{{ db_group_flags }}"
  become: true

- name: Créer l'utilisateur de la base de données
  become_user: "{{ pg_system_user }}"
  community.postgresql.postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
  become: true

- name: Ajouter l'utilisateur au groupe de la base de données
  become_user: "{{ pg_system_user }}"
  community.postgresql.postgresql_membership:
    group: "{{ db_group }}"
    target_roles: "{{ db_user }}"
    state: present
  become: true

- name: Créer la base de données et assigner le propriétaire
  become_user: "{{ pg_system_user }}"
  community.postgresql.postgresql_db:
    name: "{{ db_name }}"
    owner: "{{ db_user }}"
  become: true

- name: Exécuter les requêtes SQL d'initialisation
  become_user: "{{ pg_system_user }}"
  community.postgresql.postgresql_query:
    db: "{{ db_name }}"
    query: "{{ db_init_queries }}"
  become: true

- name: Configurer PostgreSQL pour écouter sur les interfaces réseau
  ansible.builtin.lineinfile:
    path: "{{ pg_conf_dest }}"
    regexp: '^#?listen_addresses\s*='
    line: "listen_addresses = '{{ pg_listen_addresses }}'"
  become: true
  notify: Restart PostgreSQL

- name: Autoriser localhost dans pg_hba.conf
  community.postgresql.postgresql_pg_hba:
    dest: "{{ pg_hba_conf_dest }}"
    contype: host
    databases: "{{ db_name }}"
    users: "{{ db_user }}"
    source: "{{ pg_hba_local_source }}"
    method: "{{ pg_hba_method }}"
  become: true
  notify: Restart PostgreSQL

- name: Autoriser la machine APP dans pg_hba.conf
  community.postgresql.postgresql_pg_hba:
    dest: "{{ pg_hba_conf_dest }}"
    contype: host
    databases: "{{ db_name }}"
    users: "{{ db_user }}"
    source: "{{ pg_hba_app_source }}"
    method: "{{ pg_hba_method }}"
  become: true
  notify: Restart PostgreSQL